<a href="https://colab.research.google.com/github/zzhenxi/TIL/blob/main/%5BNLP%EB%B3%B5%EC%8A%B5%5D_%EB%8B%A8%EC%96%B4%EC%9D%98_%EB%B6%84%EC%82%B0_%ED%91%9C%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

gensim 패키지를 사용하여 word2vec 인베딩 확인해보기

In [1]:
!pip install gensim --upgrade

     |████████████████████████████████| 24.1 MB 8.9 MB/s 
  Attempting uninstall: gensim
    Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0:
      Successfully uninstalled gensim-3.6.0


In [2]:
import gensim

gensim.__version__

'4.1.2'

In [3]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [4]:
for idx, word in enumerate(wv.index_to_key):
    if idx == 10:
        break

    print(f"word #{idx}/{len(wv.index_to_key)} is '{word}'")

word #0/3000000 is '</s>'
word #1/3000000 is 'in'
word #2/3000000 is 'for'
word #3/3000000 is 'that'
word #4/3000000 is 'is'
word #5/3000000 is 'on'
word #6/3000000 is '##'
word #7/3000000 is 'The'
word #8/3000000 is 'with'
word #9/3000000 is 'said'


In [5]:
vec_king = wv['king']

print(f"Embedding dimesion is : {vec_king.shape}\n")
print(f"Embedding vector of 'king' is \n\n {vec_king}")

Embedding dimesion is : (300,)

Embedding vector of 'king' is 

 [ 1.25976562e-01  2.97851562e-02  8.60595703e-03  1.39648438e-01
 -2.56347656e-02 -3.61328125e-02  1.11816406e-01 -1.98242188e-01
  5.12695312e-02  3.63281250e-01 -2.42187500e-01 -3.02734375e-01
 -1.77734375e-01 -2.49023438e-02 -1.67968750e-01 -1.69921875e-01
  3.46679688e-02  5.21850586e-03  4.63867188e-02  1.28906250e-01
  1.36718750e-01  1.12792969e-01  5.95703125e-02  1.36718750e-01
  1.01074219e-01 -1.76757812e-01 -2.51953125e-01  5.98144531e-02
  3.41796875e-01 -3.11279297e-02  1.04492188e-01  6.17675781e-02
  1.24511719e-01  4.00390625e-01 -3.22265625e-01  8.39843750e-02
  3.90625000e-02  5.85937500e-03  7.03125000e-02  1.72851562e-01
  1.38671875e-01 -2.31445312e-01  2.83203125e-01  1.42578125e-01
  3.41796875e-01 -2.39257812e-02 -1.09863281e-01  3.32031250e-02
 -5.46875000e-02  1.53198242e-02 -1.62109375e-01  1.58203125e-01
 -2.59765625e-01  2.01416016e-02 -1.63085938e-01  1.35803223e-03
 -1.44531250e-01 -5.68847

In [6]:
unk = 'cameroon'

try:
    vec_unk = wv[unk]
except KeyError:
    print(f"The word #{unk} does not appear in this model")

The word #cameroon does not appear in this model


여기서 알 수 있는 word2vec의 단점 : 모르는 단어에서는 Keyerorr가 발생한다.

In [7]:
pairs = [
    ('car', 'minivan'),   
    ('car', 'bicycle'),  
    ('car', 'airplane'),
    ('car', 'cereal'),    
    ('car', 'democracy')
]

for w1, w2 in pairs:
    print(f'{w1} ======= {w2}\t  {wv.similarity(w1, w2):.2f}')

car ======= minivan	  0.69
car ======= bicycle	  0.54
car ======= airplane	  0.42
car ======= cereal	  0.14
car ======= democracy	  0.08


In [8]:
# korea와 japan의 유사도는?
wv.similarity('korea', 'japan')

0.5648359

In [9]:
for i, (word, similarity) in enumerate(wv.most_similar(positive=['car', 'minivan'], topn=5)):
    print(f"Top {i+1} : {word}, {similarity}")

Top 1 : SUV, 0.8532192707061768
Top 2 : vehicle, 0.8175783753395081
Top 3 : pickup_truck, 0.7763688564300537
Top 4 : Jeep, 0.7567334175109863
Top 5 : Ford_Explorer, 0.7565720081329346


In [10]:
wv.most_similar(positive=['canada', 'usa'], topn=5)

[('australia', 0.7461850643157959),
 ('uk', 0.7346195578575134),
 ('india', 0.7198905944824219),
 ('canadian', 0.713864803314209),
 ('mexico', 0.6899615526199341)]

In [11]:
print(wv.doesnt_match(['fire', 'water', 'land', 'sea', 'air', 'car']))

car


fast text (word2vec방식+철자 단위 임베딩) : unknown단어에 대해서도 처리 가능!   
character n-gram    
접두사 접미사를 인식할 수 있도록 단어 앞뒤로 <>를 붙여줌    
접두사/접미사란? https://post.naver.com/viewer/postView.nhn?volumeNo=23305226&memberNo=46639488   


3-6 gram을 구해준다.    

예로 eating에 대한 5-gram을 구한다면   
<eat, eatin, ating, ting>   
eating에 대한 6-gram을 구한다면   
<eatin, eating, ating>   

이렇게 구해진 n-gram들에 대해 모두 임베딩 벡터를 구하게 된다.   
eating이라는 단어가 말뭉치 내에 있다면?   
-> skip-gram으로부터 학습한 임베딩 벡터에 위에서 얻은 character level의 n-gram 벡터를 더해줌    
eating이라는 단어가 말뭉치 내에 없다면?    
-> 더할게 없으므로 그냥 character level의 n-gram 벡터만으로 구성


gensim을 이용한 fasttext 실습

In [12]:
from pprint import pprint as print
from gensim.models.fasttext import FastText
from gensim.test.utils import datapath

# Set file names for train and test data
corpus_file = datapath('lee_background.cor')

model = FastText(vector_size=100)

# build the vocabulary
model.build_vocab(corpus_file=corpus_file)

# train the model
model.train(
    corpus_file=corpus_file, epochs=model.epochs,
    total_examples=model.corpus_count, total_words=model.corpus_total_words,
)

print(model)

In [13]:
ft = model.wv
print(ft)

#
# FastText models support vector lookups for out-of-vocabulary words by summing up character ngrams belonging to the word.
#
print(f"night => {'night' in ft.key_to_index}")
print(f"nights => {'nights' in ft.key_to_index}")

'night => True'
'nights => False'


In [14]:
print(ft['night'])

array([-0.14971754,  0.10469075, -0.2373039 , -0.09053431,  0.05325599,
        0.34626472,  0.36635157,  0.548381  ,  0.1803899 , -0.26492742,
        0.01465592, -0.13937871, -0.2697806 ,  0.58564323, -0.3616493 ,
       -0.53942084,  0.14611562, -0.22175258, -0.44538587, -0.5065588 ,
       -0.46730646,  0.00141708, -0.5256473 , -0.13251278, -0.17952877,
       -0.26496705, -0.6093761 , -0.09378491, -0.23071146,  0.2217205 ,
       -0.29421577,  0.31488836,  0.8367941 , -0.21737069,  0.2080949 ,
        0.2856565 ,  0.40098736, -0.05101724, -0.3611254 , -0.29858935,
        0.49584773, -0.4540443 ,  0.0887953 , -0.3525736 , -0.54950774,
       -0.36074337, -0.02939658,  0.17322785,  0.28879777, -0.04646828,
        0.3725494 , -0.48789063,  0.25854692, -0.42032135, -0.20470756,
       -0.23750193, -0.17839885, -0.13964088,  0.01531312, -0.32822078,
       -0.3517667 , -0.46159613, -0.26555282,  0.3763934 , -0.06675389,
        0.6932174 ,  0.05130324, -0.00541648,  0.3877058 ,  0.31

In [15]:
print(ft['nights'])

array([-1.30850106e-01,  9.19173062e-02, -2.06366822e-01, -7.85146654e-02,
        4.50116098e-02,  2.99752146e-01,  3.19793493e-01,  4.78594929e-01,
        1.57320321e-01, -2.32010663e-01,  1.44910328e-02, -1.19680725e-01,
       -2.35639155e-01,  5.07061720e-01, -3.15763623e-01, -4.69562471e-01,
        1.26338586e-01, -1.92275405e-01, -3.85837704e-01, -4.41108733e-01,
       -4.03383344e-01,  1.37968644e-04, -4.56867099e-01, -1.16648249e-01,
       -1.54737413e-01, -2.28915036e-01, -5.28422296e-01, -7.93029964e-02,
       -2.00298399e-01,  1.94283172e-01, -2.53817827e-01,  2.73211360e-01,
        7.25660980e-01, -1.88531622e-01,  1.80992708e-01,  2.47760609e-01,
        3.49971533e-01, -4.43399139e-02, -3.14136028e-01, -2.60123044e-01,
        4.30136621e-01, -3.93740922e-01,  7.66546801e-02, -3.05950940e-01,
       -4.78427202e-01, -3.12294811e-01, -2.26179175e-02,  1.51171789e-01,
        2.52420187e-01, -3.93090770e-02,  3.25372249e-01, -4.24272776e-01,
        2.25363389e-01, -

In [16]:
print(ft.similarity("night", "nights"))

0.99999183


In [17]:
print(ft.most_similar("nights"))

[('night', 0.9999918341636658),
 ('rights', 0.9999879598617554),
 ('flights', 0.9999877214431763),
 ('overnight', 0.999987006187439),
 ('fighting', 0.99998539686203),
 ('fighters', 0.9999852180480957),
 ('entered', 0.9999850988388062),
 ('fight', 0.9999849796295166),
 ('fighter', 0.9999847412109375),
 ('eight', 0.9999844431877136)]


비슷하게 생긴 (비슷한 chracter n-gram이 포함된) 단어가 많이 속해있음

In [18]:
print(ft.doesnt_match("night noon fight morning".split()))

'noon'


fasttext 임베딩 벡터는 단어의 의미보다는 단어의 모양에 더 신경쓰는 것 같기도...

In [19]:
print(ft.doesnt_match("bye hello hi mellon".split()))

'bye'


In [20]:
# 아까의 word2vec다시 한번 보자
print(wv.doesnt_match(['bye', 'hello', 'hi', 'mellon']))

'mellon'


그냥 word2vec은 잘 구별하는 것을 알 수 있다. (의미 중심으로 임베딩이 되어서 그런 듯)

In [21]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.datasets import imdb

In [22]:
tf.random.set_seed(42) # 항상 같은 결과를 도출하기 위해 전역 random seed 설정 

In [23]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=20000)
# imdb의 return은 (X_train, y_train), (X_test, y_test)형식이라고 한다.

17473536/17464789 [==============================] - 0s 0us/step


In [24]:
print(f"Train set shape : {X_train.shape}")
print(f"Test set shape : {X_test.shape}")

'Train set shape : (25000,)'
'Test set shape : (25000,)'


In [25]:
X_train[0] # 이게 뭘 한거지............! 인덱스라고 한다. 

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,

In [26]:
word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

def decode_review(text):
    """
    word_index를 받아 text를 sequence 형태로 반환하는 함수입니다.
    """
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

1654784/1641221 [==============================] - 0s 0us/step


In [27]:
decode_review(X_train[0])

"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room and it so heart shows to years of every never going and help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but when from one bit the

In [28]:
sentences = [decode_review(idx) for idx in X_train]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [29]:
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)

19999


In [30]:
X_encoded = tokenizer.texts_to_sequences(sentences)

#
max_len = max(len(sent) for sent in X_encoded)
print(max_len)

2494


In [31]:
print(f'Mean length of train set: {np.mean([len(sent) for sent in X_train], dtype=int)}')

'Mean length of train set: 238'


In [32]:
X_train=pad_sequences(X_encoded, maxlen=400, padding='post') # post는 뒤에 0을 붙여준다는 뜻
y_train=np.array(y_train)

In [33]:
embedding_matrix = np.zeros((vocab_size, 300))

print(np.shape(embedding_matrix)) # 가중치 행렬 

(19999, 300)


In [34]:
def get_vector(word):
    """
    해당 word가 word2vec에 있는 단어일 경우 임베딩 벡터를 반환
    """
    if word in wv:
        return wv[word]
    else:
        return None
 
for word, i in tokenizer.word_index.items():
    temp = get_vector(word)
    if temp is not None:
        embedding_matrix[i] = temp

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

In [39]:
model = Sequential()
model.add(Embedding(vocab_size, 300, weights=[embedding_matrix], input_length=400, trainable=False)) # trainable=False 해당 layer는 학습하지 않고 동결한다.(학습 문장에 대한 임베딩 벡터라서 딱히 학습에 포함시켜줄 필요가 없는 걸까?)
model.add(GlobalAveragePooling1D()) # 입력되는 단어 벡터의 평균을 구하는 함수입니다.
model.add(Dense(1, activation='sigmoid'))

임베딩 레이어는 어떻게 작동하는가?   
https://androidkt.com/how-embedding-layer-work-in-keras/

In [41]:
len(X_train[0])

400

In [42]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
model.fit(X_train, y_train, batch_size=64, epochs=20, validation_split=0.2)

Epoch 1/20
313/313 [==============================] - 10s 30ms/step - loss: 0.6924 - acc: 0.5242 - val_loss: 0.6908 - val_acc: 0.5852
Epoch 2/20
313/313 [==============================] - 10s 30ms/step - loss: 0.6902 - acc: 0.5735 - val_loss: 0.6884 - val_acc: 0.5944
Epoch 3/20
313/313 [==============================] - 8s 27ms/step - loss: 0.6881 - acc: 0.5885 - val_loss: 0.6861 - val_acc: 0.5974
Epoch 4/20
313/313 [==============================] - 9s 27ms/step - loss: 0.6862 - acc: 0.5910 - val_loss: 0.6838 - val_acc: 0.5904
Epoch 5/20
313/313 [==============================] - 9s 28ms/step - loss: 0.6846 - acc: 0.5944 - val_loss: 0.6825 - val_acc: 0.6024
Epoch 6/20
313/313 [==============================] - 9s 27ms/step - loss: 0.6828 - acc: 0.5952 - val_loss: 0.6801 - val_acc: 0.5934
Epoch 7/20
313/313 [==============================] - 8s 27ms/step - loss: 0.6813 - acc: 0.6016 - val_loss: 0.6788 - val_acc: 0.6104
Epoch 8/20
313/313 [==============================] - 9s 27ms/step 

밑에서부터는 이것저것 테스트

In [49]:
X_test

array([[   30,   590,   201, ...,     0,     0,     0],
       [   30,    12,    20, ...,     0,     0,     0],
       [10117,   545,     3, ...,     7,    56,   977],
       ...,
       [   30,    11,  1407, ...,     0,     0,     0],
       [   30,     9,   118, ...,     0,     0,     0],
       [   30,     4,    51, ...,     0,     0,     0]], dtype=int32)

In [43]:
test_sentences = [decode_review(idx) for idx in X_test]

X_test_encoded = tokenizer.texts_to_sequences(test_sentences)

In [44]:
X_test=pad_sequences(X_test_encoded, maxlen=400, padding='post')
y_test=np.array(y_test)

In [45]:
model.evaluate(X_test, y_test)

782/782 [==============================] - 4s 5ms/step - loss: 0.6679 - acc: 0.6102


[0.6679435968399048, 0.6101999878883362]

In [75]:
sentence = ['this is just love i like it']

In [76]:
tokenized_sen = tokenizer.texts_to_sequences(sentence)

In [73]:
a = pad_sequences(tokenized_sen, maxlen=400, padding='post')

In [74]:
model.predict(a)

array([[0.52203685],
       [0.52172965],
       [0.5198791 ],
       [0.52078205],
       [0.52094084],
       [0.5198791 ],
       [0.52078205],
       [0.52094084],
       [0.5205391 ],
       [0.5216519 ],
       [0.52078205],
       [0.52203685],
       [0.52094084],
       [0.52282614],
       [0.5220456 ],
       [0.5208798 ],
       [0.52230227],
       [0.52094084],
       [0.5198791 ],
       [0.52094084],
       [0.52282614],
       [0.5198791 ],
       [0.52388406],
       [0.52230227],
       [0.52094084],
       [0.5198791 ],
       [0.52203685]], dtype=float32)

embedding layer에 대한 설명   
https://ebbnflow.tistory.com/154   
NLP task 를 수행하기 전, 단어를 벡터로 만드는 임베딩 작업 !!!   
케라스를 이용하는 법 두가지    
1. 캐라스 내장 함수 Embedding()
2. pre trained word embedding 가져오서 embedding layer에 주입


In [ ]:
'''
[note]
이 코드는 위의 티스토리 페이지에서 가져온 코드(이해를 돕기 위함)


import numpy as np
import gensim
 
# 구글의 사전 훈련된 Word2vec 모델을 로드합니다.
word2vec_model = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz', binary=True)
 
print(word2vec_model.vectors.shape) # (3000000, 300)
 
embedding_matrix = np.zeros((vocab_size, 300)) => 이렇게 메트릭스를 만들어서 넣어준다?
# 단어 집합 크기의 행과 300개의 열을 가지는 행렬 생성. 값은 전부 0으로 채워진다.
print(np.shape(embedding_matrix)) # (16, 300)
 
def get_vector(word):
    if word in word2vec_model:
        return word2vec_model[word]
    else:
        return None
 
for word, i in t.word_index.items(): # 훈련 데이터의 단어 집합에서 단어와 정수 인덱스를 1개씩 꺼내온다.
    temp = get_vector(word) # 단어(key) 해당되는 임베딩 벡터의 300개의 값(value)를 임시 변수에 저장
    if temp is not None: # 만약 None이 아니라면 임베딩 벡터의 값을 리턴받은 것이므로
        embedding_matrix[i] = temp # 해당 단어 위치의 행에 벡터의 값을 저장한다.
 
 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
 
model = Sequential()
e = Embedding(vocab_size, 300, weights=[embedding_matrix], input_length=max_len, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)


출처: https://ebbnflow.tistory.com/154 [Dev Log : 삶은 확률의 구름]
'''